# Use postgres/example user/password credentials

services:

  db:
    image: postgres:17
    restart: always
    container_name: db
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d

  prometheus:
      image: prom/prometheus
      container_name: prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
      restart: unless-stopped
      volumes:
        - ./docker/prometheus:/etc/prometheus
        - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning/datasources

  analytics:
    image: narrative-analytics:0.1.0-SNAPSHOT
    container_name: narrative-analytics
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - DB_URL=jdbc:postgresql://db:5432/postgres

volumes:
  prom_data:

