CREATE TABLE tracked_event(
  event_id  bigint      GENERATED BY DEFAULT as IDENTITY PRIMARY KEY,
  timestamp bigint      NOT NULL,
  user_id   bigint      NOT NULL,
  event     varchar(10) NOT NULL
);
