package com.narrative.analytics.models


import com.augustnagro.magnum.Id
import com.augustnagro.magnum.PostgresDbType
import com.augustnagro.magnum.SqlNameMapper
import com.augustnagro.magnum.Table
import com.augustnagro.magnum.TableInfo

import java.time.Instant


/** Utility class to create new tracked events. Allows eventId to be autogenerated */
case class TrackedEventCreator(timestamp: Long, userId: Long, event: Event)


/** A tracked event with all information */
@Table(PostgresDbType, SqlNameMapper.CamelToSnakeCase)
case class TrackedEvent(
    @Id eventId: Long,
    timestamp: Long,
    userId: Long,
    event: Event
)


object TrackedEvent {
  val Table = TableInfo[TrackedEventCreator, TrackedEvent, Long]
}
